import Head from 'next/head'
import { useEffect, useState } from 'react'
import {
  Main,
  Aside,
  AsideMain,
  AsideButton,
  MainWrapper,
  MainHeader,
  TitleUser,
  UserLogo,
  NavBar,
  ButtonNavBar,
  InputNavBar,
  BoardsContainer,
  BoardWrapper,
  Board,
} from '@/styles/pages/home';
import Image from 'next/image';
import Logo from "../assets/logo.svg"
import Search from "../assets/search.jpeg"
import Filter from "../assets/filter.svg"
import { Data } from "./api"
import Tablet from "../assets/tablet.svg"
import People from "../assets/people.svg"
import Document from "../assets/document.svg"
import Cog from "../assets/cog.svg"
import { IData } from './api';


export default function Home() {

  const [data, setData] = useState<IData[]>()
  const [enter, setEnter] = useState(0)

  const dataButtons = [
    {
      text: "Boards",
      src: Tablet,
    },
    {
      text: "Equipes",
      src: People,
    },
    {
      text: "Relatórios",
      src: Document,
    },
    {
      text: "Ajustes",
      src: Cog,
    },
  ]

  const onDrop = (ev: React.DragEvent<HTMLDivElement>, cat: number) => {
    ev.preventDefault()
    const id = JSON.parse(ev.dataTransfer.getData("text"))
    const task = Data[id.boardId].cards[id.taskId]

    Data[id.boardId].cards.splice(id.taskId, 1)
    Data[Number(cat)].cards.splice(enter, 0, task)
    setData(Data.map(e => e))
  }

  useEffect(() => {
    setData(Data)
  }, [])

  return (
    <>
      <Head>
        <title>Vertigo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Aside>
          <Image
            src={Logo}
            alt="logo"
          />
          <AsideMain>
            {dataButtons.map((e) => {
              return (
                <AsideButton>
                  <Image
                    src={e.src}
                    alt={e.text}
                  />
                  <p>
                    {e.text}
                  </p>
                </AsideButton>
              )
            })}
          </AsideMain>
        </Aside>
        <MainWrapper>
          <MainHeader>
            <TitleUser
              value={"Meu Kanban"}
            />
            <UserLogo />
          </MainHeader>
          <NavBar>
            <ButtonNavBar>
              <Image
                src={Filter}
                alt=""
              />
              Filtrar
            </ButtonNavBar>
            <InputNavBar
              placeholder='Busque por cards, assuntos ou responsáveis...'
            />
          </NavBar>
          <BoardsContainer>
            {data?.map((e, bID) => {
              return (
                <BoardWrapper
                  onDragOver={(ev) => ev.preventDefault()}
                  onDrop={(ev) => onDrop(ev, bID)}
                >
                  <h3>{e.title}</h3>
                  <>
                    {e.cards.map((card, tID) => {
                      return (
                        <Board
                          draggable
                          onDragEnter={(ev) => setEnter(tID)}
                          onDragStart={(ev) => {
                            ev.dataTransfer.setData("text/plain", JSON.stringify({
                              boardId: bID,
                              taskId: tID
                            }))
                          }}
                        >
                          <h4>{card.title}</h4>
                          <p>{card.description}</p>
                        </Board>
                      )
                    })}
                  </>
                </BoardWrapper>
              )
            })}
          </BoardsContainer>
        </MainWrapper>
      </Main>
    </>
  )
}
